export const USER_ROLE = {
  CUSTOMER: "CUSTOMER",
  DRIVER: "DRIVER",
} as const;

export const ORDER_STATUS = {
  CREATED: "CREATED",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
} as const;